version: '3.3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: banking_app
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./creation.sql:/docker-entrypoint-initdb.d/creation.sql

volumes:
  pgdata:
